# Generated by Django 3.1.4 on 2020-12-11 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.course'),
        ),
    ]
