# Generated by Django 3.1.4 on 2020-12-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_auto_20201221_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='food_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50, verbose_name='Foodname')),
                ('food_description', models.CharField(max_length=300, verbose_name='Fooddescription')),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=50, verbose_name='password'),
        ),
    ]
