# Generated by Django 3.1.4 on 2020-12-25 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0008_auto_20201223_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('customer_first_name', models.CharField(max_length=20)),
                ('customer_last_name', models.CharField(max_length=20)),
                ('customer_phone_no', models.IntegerField()),
                ('customer_username', models.CharField(max_length=20)),
                ('customer_password', models.CharField(max_length=20)),
                ('customer_email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField()),
                ('item_name', models.CharField(max_length=50)),
                ('item_image', models.ImageField(upload_to='')),
                ('item_ingredients', models.CharField(max_length=500)),
                ('item_price', models.IntegerField()),
                ('item_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('email_address', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='food_items',
            name='food_description',
            field=models.CharField(max_length=300, verbose_name='food_description'),
        ),
        migrations.AlterField(
            model_name='food_items',
            name='food_name',
            field=models.CharField(max_length=50, verbose_name='food_name'),
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_details_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('no_of_orders', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.menu')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.user'),
        ),
    ]
