# Generated by Django 3.1.4 on 2020-12-25 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0011_auto_20201225_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('email_address', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.user'),
        ),
    ]
