# Generated by Django 3.1.4 on 2021-01-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0013_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
            ],
        ),
    ]
