# Generated by Django 3.1.4 on 2021-01-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0014_registrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='processed_by',
        ),
    ]
