# Generated by Django 3.1.4 on 2021-01-07 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0015_remove_order_processed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='menu_id',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='order_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
