# Generated by Django 3.1.4 on 2021-01-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0016_auto_20210107_1721'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registrations',
            new_name='allusers',
        ),
    ]
