# Generated by Django 3.1.4 on 2021-01-07 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='allusers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
            ],
        ),


        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='students',
            name='registration_no',
            field=models.IntegerField(verbose_name='Registration No'),
        )
    ]
