# Generated by Django 3.1.4 on 2021-01-08 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_auto_20210107_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300, verbose_name='username')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('password', models.CharField(max_length=300, verbose_name='password')),
                ('user_type', models.CharField(choices=[('Admin', 'Administrator'), ('User', 'User')], default='User', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Course Name')),
                ('code', models.CharField(max_length=6, verbose_name='Course Code')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('customer_first_name', models.CharField(max_length=20)),
                ('customer_last_name', models.CharField(max_length=20)),
                ('customer_phone_no', models.IntegerField()),
                ('customer_username', models.CharField(max_length=20)),
                ('customer_password', models.CharField(max_length=20)),
                ('customer_email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='food_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50, verbose_name='food_name')),
                ('food_description', models.CharField(max_length=300, verbose_name='food_description')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField()),
                ('item_name', models.CharField(max_length=50)),
                ('item_image', models.ImageField(upload_to='')),
                ('item_ingredients', models.CharField(max_length=500)),
                ('item_price', models.IntegerField()),
                ('item_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('zip', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.course'),
        ),
    ]
