# Generated by Django 3.1.4 on 2021-01-08 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_auto_20210108_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allusers',
            name='type',
        ),
        migrations.AddField(
            model_name='appuser',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, verbose_name='address'),
            preserve_default=False,
        ),
    ]
