# Generated by Django 3.1.4 on 2021-01-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_auto_20210108_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300, verbose_name='username')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('password', models.CharField(max_length=300, verbose_name='password')),
                ('address', models.CharField(max_length=300, verbose_name='address')),
                ('restaurentname', models.CharField(max_length=300, verbose_name='restaurentname')),
            ],
        ),
    ]
