# Generated by Django 3.1.4 on 2021-01-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_newsignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_img', models.ImageField(upload_to='')),
                ('speaciality', models.CharField(max_length=300, verbose_name='speaciality')),
            ],
        ),
        migrations.AlterField(
            model_name='newsignup',
            name='username',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='username'),
        ),
    ]
