# Generated by Django 3.1.4 on 2021-01-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_auto_20210122_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsignup',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='address'),
        ),
    ]
