# Generated by Django 3.1.4 on 2021-01-22 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0008_auto_20210122_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foodapp.newsignup'),
            preserve_default=False,
        ),
    ]
