# Generated by Django 3.1.4 on 2021-01-22 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0009_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsignup',
            name='restaurentname',
            field=models.CharField(max_length=300, null=True, verbose_name='restaurentname'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodapp.newsignup'),
        ),
    ]
