# Generated by Django 3.1.4 on 2021-01-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0010_auto_20210122_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='newsignup',
            name='restaurentimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='newsignup',
            name='restaurentspeaciality',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='restaurentspeaciality'),
        ),
        migrations.AlterField(
            model_name='newsignup',
            name='restaurentname',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='restaurentname'),
        ),
    ]
