# Generated by Django 3.1.4 on 2021-01-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0011_auto_20210122_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsignup',
            name='restaurentimage',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
    ]
