# Generated by Django 3.1.4 on 2021-01-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0013_add_catageory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_catageory',
            name='add_catagory',
        ),
        migrations.AddField(
            model_name='add_catageory',
            name='catageory',
            field=models.CharField(default=1, max_length=40, verbose_name='catageory'),
            preserve_default=False,
        ),
    ]
