# Generated by Django 3.1.4 on 2021-01-23 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0014_auto_20210123_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsignup',
            name='items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foodapp.food_items'),
            preserve_default=False,
        ),
    ]
