# Generated by Django 3.1.4 on 2021-01-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0015_newsignup_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_items',
            name='category',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='category'),
        ),
    ]
