# Generated by Django 3.1.4 on 2021-01-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0017_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catageory_name', models.CharField(max_length=300, verbose_name='catageory_name')),
                ('item_name', models.CharField(max_length=300, verbose_name='item_name')),
                ('item_price', models.CharField(max_length=300, verbose_name='item_price')),
                ('item_image', models.ImageField(max_length=300, upload_to='', verbose_name='item_image')),
                ('item_ingredents', models.ImageField(max_length=300, upload_to='', verbose_name='item_ingredents')),
            ],
        ),
    ]
