# Generated by Django 3.1.4 on 2021-01-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0018_add_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_products',
            name='item_ingredents',
            field=models.CharField(max_length=300, verbose_name='item_ingredents'),
        ),
    ]
