# Generated by Django 3.1.4 on 2021-01-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0019_auto_20210126_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_items',
            name='item_image',
            field=models.ImageField(default=1, max_length=300, upload_to='', verbose_name='item_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food_items',
            name='item_ingredents',
            field=models.CharField(default=1, max_length=300, verbose_name='item_ingredents'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food_items',
            name='item_price',
            field=models.CharField(default=1, max_length=300, verbose_name='item_price'),
            preserve_default=False,
        ),
    ]
