# Generated by Django 3.1.4 on 2021-02-14 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0021_auto_20210126_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.food_items')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_total', models.IntegerField()),
                ('items_all', models.ManyToManyField(to='foodapp.CartItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.users')),
            ],
        ),
    ]
