# Generated by Django 3.1.4 on 2021-02-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0022_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('CONFIRMED', 'CONFIRMED'), ('PROCESSING', 'PROCESSING'), ('OUT FOR DELIVARY', 'OUT FOR DELIVARY'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED'), ('RETURNED', 'RETURNED')], default='NEW', max_length=50),
        ),
        migrations.AlterField(
            model_name='food_items',
            name='food_description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='food_description'),
        ),
    ]
