# Generated by Django 3.1.4 on 2021-03-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0023_auto_20210225_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_items',
            name='item_image',
            field=models.ImageField(null=True, upload_to='static'),
        ),
    ]
