# Generated by Django 3.1.4 on 2021-03-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0028_auto_20210302_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_items',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
    ]
