# Generated by Django 3.1.4 on 2021-03-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0032_auto_20210302_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
