# Generated by Django 3.1.4 on 2021-03-04 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0033_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='item_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='item_name'),
            preserve_default=False,
        ),
    ]
