# Generated by Django 3.1.4 on 2021-03-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0035_auto_20210304_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='item_image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
